name: Push to Azure Container Registry

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

jobs:
  push-to-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: audioflow.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Pull and tag Docker image from Docker Hub
      run: |
        docker pull benjh4/express-test:latest
        docker tag benjh4/express-test:latest audioflow.azurecr.io/express-test:latest

    - name: Push Docker image to Azure Container Registry
      run: docker push audioflow.azurecr.io/express-test:latest
