name: Push to Azure Container Registry

on:
  workflow_run:
    workflows: ["Docker Build & Push"]
    types:
      - completed

jobs:
  push-to-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: audioflow.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Check if the image exists in Azure Container Registry
      id: check-image-exists
      run: |
        IMAGE="audioflow.azurecr.io/express-test:latest"
        if docker manifest inspect $IMAGE > /dev/null 2>&1; then
          echo "::set-output name=image_exists::true"
        else
          echo "::set-output name=image_exists::false"
        fi

    - name: Delete Docker image from Azure Container Registry if it exists
      if: steps.check-image-exists.outputs.image_exists == 'true'
      run: |
        docker image rm -f audioflow.azurecr.io/express-test:latest

    - name: Pull and tag Docker image from Docker Hub
      run: |
        docker pull benjh4/test-express:latest
        docker tag benjh4/test-express:latest audioflow.azurecr.io/express-test:latest


    - name: Push Docker image to Azure Container Registry
      run: docker push audioflow.azurecr.io/express-test:latest

